// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/OpenCHAMI/metadata-service/internal/storage"
	"github.com/OpenCHAMI/metadata-service/pkg/wireguard"
)

// Config holds all configuration for the service
type Config struct {
	// Server Configuration
	Port         int    `mapstructure:"port"`
	Host         string `mapstructure:"host"`
	ReadTimeout  int    `mapstructure:"read_timeout"`
	WriteTimeout int    `mapstructure:"write_timeout"`
	IdleTimeout  int    `mapstructure:"idle_timeout"`

	// Storage Configuration
	DataDir string `mapstructure:"data_dir"`

	// WireGuard Configuration
	WireGuardStateFile            string `mapstructure:"wireguard_state_file"`
	WireGuardOnly                 bool   `mapstructure:"wireguard_only"`
	TokenSmithURL                 string `mapstructure:"tokensmith_url"`
	TokenSmithBootstrapToken      string `mapstructure:"tokensmith_bootstrap_token"`
	TokenSmithServiceIdentityCert string `mapstructure:"tokensmith_service_identity_cert"`
	TokenSmithServiceIdentityKey  string `mapstructure:"tokensmith_service_identity_key"`
	TokenSmithServiceIdentityCA   string `mapstructure:"tokensmith_service_identity_ca"`
	TokenSmithTargetService       string `mapstructure:"tokensmith_target_service"`
	TokenSmithScopes              string `mapstructure:"tokensmith_scopes"`
	TokenSmithRefreshSkewSec      int    `mapstructure:"tokensmith_refresh_skew_sec"`
	TokenSmithScopeHint           string `mapstructure:"tokensmith_scope_hint"`

	// SMD Integration Configuration
	SMDSyncEnabled  bool `mapstructure:"smd_sync_enabled"`
	SMDSyncInterval int  `mapstructure:"smd_sync_interval"`

	// Feature Flags
	Debug bool `mapstructure:"debug"`
}

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	return &Config{
		Port:         8080,
		Host:         "0.0.0.0",
		ReadTimeout:  15,
		WriteTimeout: 15,
		IdleTimeout:  60,

		DataDir: "/data",

		WireGuardStateFile:            "/data/wireguard/state.yaml",
		WireGuardOnly:                 false,
		TokenSmithURL:                 "",
		TokenSmithBootstrapToken:      "",
		TokenSmithServiceIdentityCert: "",
		TokenSmithServiceIdentityKey:  "",
		TokenSmithServiceIdentityCA:   "",
		TokenSmithTargetService:       "smd",
		TokenSmithScopes:              "",
		TokenSmithRefreshSkewSec:      300,
		TokenSmithScopeHint:           "",

		SMDSyncEnabled:  true,
		SMDSyncInterval: 60,

		Debug: false,
	}
}

var (
	cfgFile string
	config  *Config
	mockSMD bool
)

var notifyShutdownSignals = func(ch chan<- os.Signal) {
	signal.Notify(ch, syscall.SIGINT, syscall.SIGTERM)
}

var stopShutdownSignalNotify = func(ch chan<- os.Signal) {
	signal.Stop(ch)
}

var registerServerIntegrations = registerCustomServerIntegrations

var currentWGController *wireguard.Controller

func main() {
	if err := rootCmd.Execute(); err != nil {
		log.Fatal(err)
	}
}

var rootCmd = &cobra.Command{
	Use:   "github.com/OpenCHAMI/metadata-service",
	Short: "",
	Long:  `github.com/OpenCHAMI/metadata-service - A Fabrica-generated OpenCHAMI service`,
	RunE:  runServer,
}

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start the github.com/OpenCHAMI/metadata-service server",
	Long:  `Start the github.com/OpenCHAMI/metadata-service HTTP server with the configured options`,
	RunE:  runServer,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.ochami-metadata.yaml)")
	rootCmd.PersistentFlags().Bool("debug", false, "Enable debug logging")
	rootCmd.PersistentFlags().BoolVar(&mockSMD, "mock-smd", false, "Use built-in mock SMD data instead of requiring SMD_URL")

	// Server flags
	serveCmd.Flags().IntP("port", "p", 8080, "Port to listen on")
	serveCmd.Flags().String("host", "0.0.0.0", "Host to bind to")
	serveCmd.Flags().Int("read-timeout", 15, "Read timeout in seconds")
	serveCmd.Flags().Int("write-timeout", 15, "Write timeout in seconds")
	serveCmd.Flags().Int("idle-timeout", 60, "Idle timeout in seconds")

	serveCmd.Flags().String("data-dir", "/data", "Directory for file storage")

	// WireGuard flags
	serveCmd.Flags().String("wireguard-state-file", "/data/wireguard/state.yaml", "Path to WireGuard state file for persistence")
	serveCmd.Flags().Bool("wireguard-only", false, "Restrict access to WireGuard network only")

	// SMD sync flags
	serveCmd.Flags().Bool("smd-sync-enabled", true, "Enable background SMD cache sync worker")
	serveCmd.Flags().Int("smd-sync-interval", 60, "SMD cache sync interval in seconds")

	// Bind flags to viper
	viper.BindPFlags(serveCmd.Flags())
	viper.BindPFlags(rootCmd.PersistentFlags())
	registerDashAliases(rootCmd.PersistentFlags(), serveCmd.Flags())

	// Add subcommands
	rootCmd.AddCommand(serveCmd)
}

func initConfig() {
	config = DefaultConfig()

	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		// Search for config in home directory
		home, err := os.UserHomeDir()
		cobra.CheckErr(err)

		viper.AddConfigPath(home)
		viper.AddConfigPath(".")
		viper.SetConfigType("yaml")
		viper.SetConfigName(".ochami-metadata")
	}

	// Environment variables
	viper.SetEnvPrefix("OCHAMI_METADATA")
	viper.AutomaticEnv()

	// Read config file if it exists
	if err := viper.ReadInConfig(); err == nil {
		log.Printf("Using config file: %s", viper.ConfigFileUsed())
	}

	// Unmarshal config
	if err := viper.Unmarshal(config); err != nil {
		log.Fatalf("Unable to decode into config struct: %v", err)
	}

	// Set debug logging
	if config.Debug {
		log.SetFlags(log.LstdFlags | log.Lshortfile)
		log.Println("Debug logging enabled")
	}
}

func runServer(cmd *cobra.Command, args []string) error {
	log.Printf("Starting github.com/OpenCHAMI/metadata-service server...")

	appCtx, appCancel := context.WithCancel(context.Background())
	defer appCancel()

	if err := storage.InitFileBackend(config.DataDir); err != nil {
		return fmt.Errorf("failed to initialize file storage: %w", err)
	}
	log.Printf("File storage initialized in %s", config.DataDir)

	// Setup router
	r := chi.NewRouter()

	// Add middleware
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)

	if config.Debug {
		r.Mount("/debug", middleware.Profiler())
	}

	if err := registerServerIntegrations(appCtx, r); err != nil {
		return err
	}

	// Public service endpoints (outside WG middleware).
	r.Get("/health", healthHandler)
	r.Get("/openapi.json", ServeOpenAPISpec)
	r.Get("/docs", ServeSwaggerUI)

	reconcileRuntime, err := newReconciliationRuntimeFn(currentWGController)
	if err != nil {
		return fmt.Errorf("failed to initialize reconciliation runtime: %w", err)
	}
	go func() {
		<-appCtx.Done()
		if stopErr := reconcileRuntime.Stop(); stopErr != nil {
			log.Printf("Failed to stop reconciliation runtime cleanly: %v", stopErr)
		}
	}()

	// Create HTTP server
	addr := fmt.Sprintf("%s:%d", config.Host, config.Port)
	server := &http.Server{
		Addr:         addr,
		Handler:      r,
		ReadTimeout:  time.Duration(config.ReadTimeout) * time.Second,
		WriteTimeout: time.Duration(config.WriteTimeout) * time.Second,
		IdleTimeout:  time.Duration(config.IdleTimeout) * time.Second,
	}

	// Start server in goroutine
	go func() {
		log.Printf("Server starting on %s", addr)
		log.Printf("Storage: file backend in %s", config.DataDir)

		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server failed: %v", err)
		}
	}()

	// Wait for interrupt signal for graceful shutdown
	quit := make(chan os.Signal, 1)
	notifyShutdownSignals(quit)
	defer stopShutdownSignalNotify(quit)
	<-quit
	log.Println("Server shutting down...")
	appCancel()

	// Graceful shutdown with timeout
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		return fmt.Errorf("server forced to shutdown: %w", err)
	}

	log.Println("Server exited")
	return nil
}

// Health check handler
func healthHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	payload := map[string]string{
		"status":  "healthy",
		"service": "github.com/OpenCHAMI/metadata-service",
	}
	statusCode := http.StatusOK

	if currentSMDHealth != nil {
		if healthy, reason := currentSMDHealth.InitialSyncStatus(); !healthy {
			statusCode = http.StatusServiceUnavailable
			payload["status"] = "unhealthy"
			if reason != "" {
				payload["reason"] = reason
			}
		}
	}

	w.WriteHeader(statusCode)
	_ = json.NewEncoder(w).Encode(payload)
}
